COPY google.address_descriptors FROM 'project_data_export/google_address_descriptors.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY google.operating_hours FROM 'project_data_export/google_operating_hours.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY google.photos FROM 'project_data_export/google_photos.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY google.places FROM 'project_data_export/google_places.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY mn_gis.dnr_management_units_prk FROM 'project_data_export/mn_gis_dnr_management_units_prk.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY mn_gis.dnr_management_units_prk_ref_pts FROM 'project_data_export/mn_gis_dnr_management_units_prk_ref_pts.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY mn_gis.dnr_stat_plan_areas_prk FROM 'project_data_export/mn_gis_dnr_stat_plan_areas_prk.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY nps.activities FROM 'project_data_export/nps_activities.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.addresses FROM 'project_data_export/nps_addresses.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.amenities FROM 'project_data_export/nps_amenities.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.campgrounds FROM 'project_data_export/nps_campgrounds.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.campground_amenities FROM 'project_data_export/nps_campground_amenities.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.campground_campsites FROM 'project_data_export/nps_campground_campsites.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.contact_email_addresses FROM 'project_data_export/nps_contact_email_addresses.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.contact_phone_numbers FROM 'project_data_export/nps_contact_phone_numbers.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.entrance_fees FROM 'project_data_export/nps_entrance_fees.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.entrance_passes FROM 'project_data_export/nps_entrance_passes.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.fees FROM 'project_data_export/nps_fees.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.images FROM 'project_data_export/nps_images.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.multimedia FROM 'project_data_export/nps_multimedia.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.operating_hours FROM 'project_data_export/nps_operating_hours.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.operating_hours_exceptions FROM 'project_data_export/nps_operating_hours_exceptions.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.parks FROM 'project_data_export/nps_parks.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.topics FROM 'project_data_export/nps_topics.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY ridb.Activities_API_v1 FROM 'project_data_export/ridb_activities_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.CampsiteAttributes_API_v1 FROM 'project_data_export/ridb_campsiteattributes_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Campsites_API_v1 FROM 'project_data_export/ridb_campsites_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.EntityActivities_API_v1 FROM 'project_data_export/ridb_entityactivities_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Events_API_v1 FROM 'project_data_export/ridb_events_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Facilities_API_v1 FROM 'project_data_export/ridb_facilities_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.FacilityAddresses_API_v1 FROM 'project_data_export/ridb_facilityaddresses_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Links_API_v1 FROM 'project_data_export/ridb_links_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Media_API_v1 FROM 'project_data_export/ridb_media_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.MemberTours_API_v1 FROM 'project_data_export/ridb_membertours_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Organizations_API_v1 FROM 'project_data_export/ridb_organizations_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.OrgEntities_API_v1 FROM 'project_data_export/ridb_orgentities_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.PermitEntranceAttributes_API_v1 FROM 'project_data_export/ridb_permitentranceattributes_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.PermitEntrances_API_v1 FROM 'project_data_export/ridb_permitentrances_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.PermitEntranceZones_API_v1 FROM 'project_data_export/ridb_permitentrancezones_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.PermittedEquipment_API_v1 FROM 'project_data_export/ridb_permittedequipment_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.RecAreaAddresses_API_v1 FROM 'project_data_export/ridb_recareaaddresses_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.RecAreaFacilities_API_v1 FROM 'project_data_export/ridb_recareafacilities_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.RecAreas_API_v1 FROM 'project_data_export/ridb_recareas_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.TourAttributes_API_v1 FROM 'project_data_export/ridb_tourattributes_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Tours_API_v1 FROM 'project_data_export/ridb_tours_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
