COPY google.address_descriptors FROM 'project_data_export/google_address_descriptors.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY google.operating_hours FROM 'project_data_export/google_operating_hours.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY google.photos FROM 'project_data_export/google_photos.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY google.places FROM 'project_data_export/google_places.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY mn_dnr.extracted_table_0 FROM 'project_data_export/mn_dnr_extracted_table__.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY mn_dnr.extracted_table_1 FROM 'project_data_export/mn_dnr_extracted_table___1.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY mn_gis.dnr_management_units_prk FROM 'project_data_export/mn_gis_dnr_management_units_prk.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY mn_gis.dnr_management_units_prk_ref_pts FROM 'project_data_export/mn_gis_dnr_management_units_prk_ref_pts.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY mn_gis.dnr_stat_plan_areas_prk FROM 'project_data_export/mn_gis_dnr_stat_plan_areas_prk.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY mn_gis.state_forest_campgrounds_and_day_use_areas FROM 'project_data_export/mn_gis_state_forest_campgrounds_and_day_use_areas.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY mn_gis.state_forest_campgrounds_and_day_use_areas_orig FROM 'project_data_export/mn_gis_state_forest_campgrounds_and_day_use_areas_orig.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY normalized.AddressTypes FROM 'project_data_export/normalized_addresstypes.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('name', 'description', 'created_dt', 'updated_dt', 'address_type_key'));
COPY normalized.DataSources FROM 'project_data_export/normalized_datasources.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('name', 'description', 'created_dt', 'updated_dt', 'data_source_key'));
COPY normalized.LocationTypes FROM 'project_data_export/normalized_locationtypes.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('name', 'description', 'created_dt', 'updated_dt', 'location_type_key'));
COPY normalized.MediaTypes FROM 'project_data_export/normalized_mediatypes.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('name', 'description', 'created_dt', 'updated_dt', 'media_type_key'));
COPY normalized.WebsiteTypes FROM 'project_data_export/normalized_websitetypes.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('name', 'description', 'created_dt', 'updated_dt', 'website_type_key'));
COPY nps.activities FROM 'project_data_export/nps_activities.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.addresses FROM 'project_data_export/nps_addresses.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.amenities FROM 'project_data_export/nps_amenities.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.campgrounds FROM 'project_data_export/nps_campgrounds.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.campground_amenities FROM 'project_data_export/nps_campground_amenities.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.campground_campsites FROM 'project_data_export/nps_campground_campsites.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.contact_email_addresses FROM 'project_data_export/nps_contact_email_addresses.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.contact_phone_numbers FROM 'project_data_export/nps_contact_phone_numbers.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.entrance_fees FROM 'project_data_export/nps_entrance_fees.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.entrance_passes FROM 'project_data_export/nps_entrance_passes.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.fees FROM 'project_data_export/nps_fees.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.images FROM 'project_data_export/nps_images.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.multimedia FROM 'project_data_export/nps_multimedia.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.operating_hours FROM 'project_data_export/nps_operating_hours.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.operating_hours_exceptions FROM 'project_data_export/nps_operating_hours_exceptions.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.parks FROM 'project_data_export/nps_parks.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY nps.topics FROM 'project_data_export/nps_topics.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null 'id');
COPY ridb.Activities_API_v1 FROM 'project_data_export/ridb_activities_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.CampsiteAttributes_API_v1 FROM 'project_data_export/ridb_campsiteattributes_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Campsites_API_v1 FROM 'project_data_export/ridb_campsites_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.EntityActivities_API_v1 FROM 'project_data_export/ridb_entityactivities_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Events_API_v1 FROM 'project_data_export/ridb_events_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Facilities_API_v1 FROM 'project_data_export/ridb_facilities_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.FacilityAddresses_API_v1 FROM 'project_data_export/ridb_facilityaddresses_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Links_API_v1 FROM 'project_data_export/ridb_links_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Media_API_v1 FROM 'project_data_export/ridb_media_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.MemberTours_API_v1 FROM 'project_data_export/ridb_membertours_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Organizations_API_v1 FROM 'project_data_export/ridb_organizations_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.OrgEntities_API_v1 FROM 'project_data_export/ridb_orgentities_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.PermitEntranceAttributes_API_v1 FROM 'project_data_export/ridb_permitentranceattributes_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.PermitEntrances_API_v1 FROM 'project_data_export/ridb_permitentrances_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.PermitEntranceZones_API_v1 FROM 'project_data_export/ridb_permitentrancezones_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.PermittedEquipment_API_v1 FROM 'project_data_export/ridb_permittedequipment_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.RecAreaAddresses_API_v1 FROM 'project_data_export/ridb_recareaaddresses_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.RecAreaFacilities_API_v1 FROM 'project_data_export/ridb_recareafacilities_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.RecAreas_API_v1 FROM 'project_data_export/ridb_recareas_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.TourAttributes_API_v1 FROM 'project_data_export/ridb_tourattributes_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY ridb.Tours_API_v1 FROM 'project_data_export/ridb_tours_api_v_.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"');
COPY normalized.Locations FROM 'project_data_export/normalized_locations.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('name', 'data_source_key', 'location_type_key', 'latitude', 'longitude', 'directions_info', 'weather_info', 'ai_generative_description', 'description', 'state_abbre', 'state', 'active_flag', 'created_dt', 'updated_dt', 'location_key'));
COPY normalized.Media FROM 'project_data_export/normalized_media.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('media_type_key', 'location_key', 'credit', 'title', 'altText', 'caption', 'url', 'subtitle', 'height', 'width', 'third_party_key', 'created_dt', 'updated_dt', 'media_key'));
COPY normalized.OperatingHours FROM 'project_data_export/normalized_operatinghours.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('location_key', 'name', 'description', 'type', 'timezone', 'created_dt', 'updated_dt', 'operating_hours_key'));
COPY normalized.OperatingHoursTimes FROM 'project_data_export/normalized_operatinghourstimes.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('operating_hours_key', 'descriptive_time', 'created_dt', 'updated_dt', 'operating_hours_time_key'));
COPY normalized.Websites FROM 'project_data_export/normalized_websites.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('website_type_key', 'location_key', 'url', 'description', 'created_dt', 'updated_dt', 'website_key'));
COPY normalized.Addresses FROM 'project_data_export/normalized_addresses.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('location_key', 'address_type_key', 'postal_code', 'city', 'state_abbre', 'state', 'address_line_1', 'address_line_2', 'address_line_3', 'county', 'country_code', 'created_dt', 'updated_dt', 'address_key'));
COPY normalized.ContactEmailAddresses FROM 'project_data_export/normalized_contactemailaddresses.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('location_key', 'email_address', 'description', 'type', 'created_dt', 'updated_dt', 'contact_email_address_key'));
COPY normalized.ContactPhoneNumbers FROM 'project_data_export/normalized_contactphonenumbers.csv' (FORMAT 'csv', header 1, delimiter ',', quote '"', force_not_null ('location_key', 'phone_number', 'description', 'extension', 'type', 'created_dt', 'updated_dt', 'contact_phone_number_key'));
